name: concurrent_executor
description: a concurrent task executor
version: 0.9.0
repository: "https://github.com/Silentdoer/concurrent_executor.git"
publish_to: "https://pub.dartlang.org"

environment:
  sdk: '>=2.14.2 <3.0.0'

dependencies:
  logging: ^1.0.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  meta: ^1.7.0