name: concurrent_executor
description: a concurrent task executor
version: 0.7.1
repository: "https://github.com/Silentdoer/concurrent_executor.git"
publish_to: "https://pub.dartlang.org"

environment:
  sdk: '>=2.13.1 <3.0.0'

dependencies:
  logging: ^1.0.1

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  meta: ^1.4.0